### ISSUE TITLE
when example project is run after godot export->ends in message->unfortunately app has stopped working

### ISSUE THREAD

**Issue by CyborgNinja021** [j1and1/GodotUnityAdsInterface#6]
when example project is run after godot export->ends in message when run->unfortunately app has stopped working.
what could be the reason for that? is there any unity library has to be added if yes-> where in the sample project?.thankyou

**Comment by j1and1** [comment]
Currently example project does not contain full export template setup. So you will have to go through the setup section of the readme to get it running.

**Comment by j1and1** [comment]
@CyborgNinja021 Also can you please provide LogCat output for the crash you mentioned?
